apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixel-dog-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pixel-dog-web
  template:
    metadata:
      labels:
        app: pixel-dog-web
    spec:
      containers:
        - name: pixel-dog-web
          image: ghcr.io/romanshkvolkov/pixel-dog-web:latest
          ports:
            - containerPort: 3000
