apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pixel-dog-route
  namespace: default
spec:
  parentRefs:
    - name: gateway-api
      namespace: default

  hostnames:
    - "pixel-dog.guz-studio.dev"

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

      backendRefs:
        - name: pixel-dog-web
          port: 80
